"use client";

import React from "react";
import Link from "next/link";
import { Navbar } from "../../components/Navbar";
import { Footer } from "../../components/Footer";
import { 
  Scale, ShieldCheck, CheckCircle2, AlertTriangle, ShieldAlert, 
  Database, Lock, BookOpen, FileText, ArrowRight, HelpCircle
} from "lucide-react";

export default function AboutTrustPage() {
  return (
    <div className="min-h-screen flex flex-col bg-parchment">
      <Navbar />

      <main className="flex-1 max-w-5xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
        
        {/* Header Hero */}
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-forest-light border border-forest/30 text-forest text-xs font-bold uppercase tracking-wide">
            <ShieldCheck className="w-4 h-4" />
            Institutional Legal Trust Framework
          </div>

          <h1 className="serif-heading text-3xl sm:text-5xl font-bold text-ink leading-tight">
            How RightPath Guarantees Legal Accuracy & Verification
          </h1>

          <p className="text-sm sm:text-base text-ink-muted leading-relaxed">
            Every legal citation generated by RightPath is grounded directly in official statutory text from ChromaDB vector stores — never invented by AI models.
          </p>
        </div>

        {/* Pillar 1: RAG Statutory Grounding */}
        <div className="bg-parchment-card border border-border-card p-8 rounded-lg space-y-6 shadow-sm">
          <div className="flex items-center gap-3 border-b border-border-subtle pb-4">
            <div className="w-10 h-10 rounded-md bg-saffron text-parchment flex items-center justify-center font-bold">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="serif-heading text-xl font-bold text-ink">1. Vector Retrieval-Augmented Generation (RAG)</h2>
              <p className="text-xs text-ink-muted">Zero hallucination guarantee on statutory citations</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-xs text-ink-muted leading-relaxed">
            <div className="space-y-3">
              <h3 className="font-bold text-ink text-sm">Indexed Statutory Acts</h3>
              <p>
                RightPath indexes the complete, un-edited legal text of the <strong>Right to Information (RTI) Act, 2005</strong>, <strong>Consumer Protection Act, 2019</strong>, and land compensation acts into ChromaDB vector databases using high-dimensional embeddings.
              </p>
            </div>

            <div className="space-y-3">
              <h3 className="font-bold text-ink text-sm">Direct Citation Verification</h3>
              <p>
                When you describe a grievance, the system retrieves exact matching chunks (e.g. Section 6(1), Section 7(1), Section 8(1) exemptions) and embeds them directly into your drafted RTI application. Floating or un-verified text is strictly prohibited.
              </p>
            </div>
          </div>

          <div className="p-4 rounded bg-forest-light border border-forest/30 flex items-center justify-between text-xs font-semibold text-forest">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4" />
              <span>All citations bear the official &quot;✓ Verified from RTI Act, 2005&quot; badge</span>
            </div>
          </div>
        </div>

        {/* Pillar 2: Confidence-Tier System */}
        <div id="confidence-tiers" className="bg-parchment-card border border-border-card p-8 rounded-lg space-y-6 shadow-sm">
          <div className="flex items-center gap-3 border-b border-border-subtle pb-4">
            <div className="w-10 h-10 rounded-md bg-saffron text-parchment flex items-center justify-center font-bold">
              <Scale className="w-5 h-5" />
            </div>
            <div>
              <h2 className="serif-heading text-xl font-bold text-ink">2. The 3-Tier Confidence & Safety Framework</h2>
              <p className="text-xs text-ink-muted">Understanding why certain grievances require formal counsel</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {/* Tier 1: Settled */}
            <div className="p-5 rounded bg-parchment border-2 border-forest space-y-3">
              <span className="px-2.5 py-1 rounded-full bg-forest-light text-forest text-[11px] font-bold uppercase tracking-wider">
                Settled Scope
              </span>
              <h3 className="serif-heading font-bold text-base text-ink">Standard Civic Queries</h3>
              <p className="text-xs text-ink-muted leading-relaxed">
                Straightforward public works, potholes, water supply, electricity billing, and government expenditure logs. Automated drafting proceeds immediately.
              </p>
            </div>

            {/* Tier 2: Jurisdiction Dependent */}
            <div className="p-5 rounded bg-parchment border-2 border-saffron space-y-3">
              <span className="px-2.5 py-1 rounded-full bg-saffron-light text-saffron text-[11px] font-bold uppercase tracking-wider">
                Jurisdiction Dependent
              </span>
              <h3 className="serif-heading font-bold text-base text-ink">Location Clarification</h3>
              <p className="text-xs text-ink-muted leading-relaxed">
                Standard civic issues that require PIN code or ward office confirmation to map to the correct Public Information Officer (PIO).
              </p>
            </div>

            {/* Tier 3: Needs Lawyer */}
            <div className="p-5 rounded bg-parchment border-2 border-crimson space-y-3">
              <span className="px-2.5 py-1 rounded-full bg-crimson-light text-crimson text-[11px] font-bold uppercase tracking-wider">
                Requires Counsel
              </span>
              <h3 className="serif-heading font-bold text-base text-crimson">Hard Refusal State</h3>
              <p className="text-xs text-ink-muted leading-relaxed">
                Disputes involving ongoing civil lawsuits, serious criminal matters, or exempted records under Section 8. Drafting is locked and legal aid directory is provided.
              </p>
            </div>

          </div>
        </div>

        {/* Pillar 3: 2-Step Reply-First Interaction Model */}
        <div className="bg-parchment-card border border-border-card p-8 rounded-lg space-y-6 shadow-sm">
          <div className="flex items-center gap-3 border-b border-border-subtle pb-4">
            <div className="w-10 h-10 rounded-md bg-saffron text-parchment flex items-center justify-center font-bold">
              <BookOpen className="w-5 h-5" />
            </div>
            <div>
              <h2 className="serif-heading text-xl font-bold text-ink">3. 2-Step Confirm-Then-Draft Interaction Model</h2>
              <p className="text-xs text-ink-muted">Eliminating single-shot opaque AI generation</p>
            </div>
          </div>

          <div className="space-y-4 text-xs text-ink-muted leading-relaxed">
            <p>
              Traditional AI legal applications attempt to generate full legal documents in a single black-box response. RightPath completely decouples input understanding from document drafting:
            </p>
            <ol className="list-decimal pl-5 space-y-2 text-ink">
              <li><strong>Extraction Phase:</strong> The system analyzes your grievance and presents an &quot;Understanding Confirmation&quot; screen displaying extracted fields (Issue, Department, Location, Confidence Tier).</li>
              <li><strong>Verification Phase:</strong> You review and edit the extracted parameters.</li>
              <li><strong>Drafting Phase:</strong> Only upon your explicit confirmation does the engine construct the official application document.</li>
            </ol>
          </div>
        </div>

        {/* Bottom Callout */}
        <div className="text-center space-y-4 pt-4">
          <h2 className="serif-heading text-2xl font-bold text-ink">Empower your legal rights with institutional authority.</h2>
          <Link
            href="/rti/new-case"
            className="inline-flex items-center gap-2 px-8 py-4 rounded bg-saffron text-parchment font-semibold text-sm shadow hover:bg-saffron-hover transition-colors"
          >
            <span>Start Your RTI Case Now</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>

      </main>

      <Footer />
    </div>
  );
}
